from django.contrib.auth.models import User
from django.db import models

class FavouriteModel(models.Model):
    Brand = models.CharField(max_length=128, name='brand', default=None)
    DeviceName = models.CharField(max_length=128, name='device_name', default=None)
    _2g_bands = models.CharField(max_length=128, name='_2g_bands', default=None)
    _3_5mm_jack = models.CharField(max_length=128, name='_3_5mm_jack', default=None)
    _3g_bands = models.CharField(max_length=128, name='_3g_bands', default=None)
    _4g_bands = models.CharField(max_length=128, name='_4g_bands', default=None)
    alert_types = models.CharField(max_length=128, name='alert_types', default=None)
    announced = models.CharField(max_length=128, name='announced', default=None)
    audio_quality = models.CharField(max_length=128, name='audio_quality', default=None)
    battery_c = models.CharField(max_length=128, name='battery_c', default=None)
    bluetooth = models.CharField(max_length=128, name='bluetooth', default=None)
    body_c = models.CharField(max_length=128, name='body_c', default=None)
    browser = models.CharField(max_length=128, name='browser', default=None)
    build = models.CharField(max_length=128, name='build', default=None)
    call_records = models.CharField(max_length=128, name='call_records', default=None)
    camera = models.CharField(max_length=128, name='camera', default=None)
    camera_c = models.CharField(max_length=128, name='camera_c', default=None)
    card_slot = models.CharField(max_length=128, name='card_slot', default=None)
    chipset = models.CharField(max_length=128, name='chipset', default=None)
    colors = models.CharField(max_length=128, name='colors', default=None)
    cpu = models.CharField(max_length=128, name='cpu', default=None)
    dimensions = models.CharField(max_length=128, name='dimensions', default=None)
    display = models.CharField(max_length=128, name='display', default=None)
    display_c = models.CharField(max_length=128, name='display_c', default=None)
    edge = models.CharField(max_length=128, name='edge', default=None)
    features = models.CharField(max_length=128, name='features', default=None)
    features_c = models.CharField(max_length=128, name='features_c', default=None)
    games = models.CharField(max_length=128, name='games', default=None)
    gprs = models.CharField(max_length=128, name='gprs', default=None)
    gps = models.CharField(max_length=128, name='gps', default=None)
    gpu = models.CharField(max_length=128, name='gpu', default=None)
    infrared_port = models.CharField(max_length=128, name='infrared_port', default=None)
    internal = models.CharField(max_length=128, name='internal', default=None)
    java = models.CharField(max_length=128, name='java', default=None)
    keyboard = models.CharField(max_length=128, name='keyboard', default=None)
    loudspeaker = models.CharField(max_length=128, name='loudspeaker', default=None)
    loudspeaker_check = models.CharField(max_length=128, name='loudspeaker_check', default=None)
    memory_c = models.CharField(max_length=128, name='memory_c', default=None)
    messaging = models.CharField(max_length=128, name='messaging', default=None)
    multitouch = models.CharField(max_length=128, name='multitouch', default=None)
    music_play = models.CharField(max_length=128, name='music_play', default=None)
    network_c = models.CharField(max_length=128, name='network_c', default=None)
    nfc = models.CharField(max_length=128, name='nfc', default=None)
    os = models.CharField(max_length=128, name='os', default=None)
    performance = models.CharField(max_length=128, name='performance', default=None)
    phonebook = models.CharField(max_length=128, name='phonebook', default=None)
    price = models.CharField(max_length=128, name='price', default=None)
    primary = models.CharField(max_length=128, name='primary', default=None)
    protection = models.CharField(max_length=128, name='protection', default=None)
    radio = models.CharField(max_length=128, name='radio', default=None)
    resolution = models.CharField(max_length=128, name='resolution', default=None)
    sar = models.CharField(max_length=128, name='sar', default=None)
    sar_eu = models.CharField(max_length=128, name='sar_eu', default=None)
    sar_us = models.CharField(max_length=128, name='sar_us', default=None)
    secondary = models.CharField(max_length=128, name='secondary', default=None)
    sensors = models.CharField(max_length=128, name='sensors', default=None)
    sim = models.CharField(max_length=128, name='sim', default=None)
    size = models.CharField(max_length=128, name='size', default=None)
    sound_c = models.CharField(max_length=128, name='sound_c', default=None)
    speed = models.CharField(max_length=128, name='speed', default=None)
    stand_by = models.CharField(max_length=128, name='stand_by', default=None)
    status = models.CharField(max_length=128, name='status', default=None)
    talk_time = models.CharField(max_length=128, name='talk_time', default=None)
    technology = models.CharField(max_length=128, name='technology', default=None)
    type = models.CharField(max_length=128, name='type', default=None)
    usb = models.CharField(max_length=128, name='usb', default=None)
    video = models.CharField(max_length=128, name='video', default=None)
    weight = models.CharField(max_length=128, name='weight', default=None)
    wlan = models.CharField(max_length=128, name='wlan', default=None)
    user = models.ForeignKey(User)


class HiddenModel(models.Model):
    to_db = models.TextField()
    user = models.ForeignKey(User)